language: java

sudo: required

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

# install Arial font (msttcorefonts) for charts
# after that, install OpenSSL 1.0.2d for Netty tcnative dependency (which is enabled by setOpenSSL(true) in the HTTP client)

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cabextract
  - echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
  - sudo apt-get install ttf-mscorefonts-installer
  - sudo apt-get install x-ttcidfont-conf
  - sudo mkfontdir
  - sudo apt-get install -y libapr1
  - wget http://mirrors.kernel.org/ubuntu/pool/main/o/openssl/libssl1.0.0_1.0.2d-0ubuntu1_amd64.deb
  - wget http://mirrors.kernel.org/ubuntu/pool/main/o/openssl/openssl_1.0.2d-0ubuntu1_amd64.deb
  - sudo dpkg -i libssl1.0.0_1.0.2d-0ubuntu1_amd64.deb
  - sudo dpkg -i openssl_1.0.2d-0ubuntu1_amd64.deb

install: true
